name: CI

on: push

jobs:
  build:
    name: Lint, Build, Test & Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ secrets.CACHE_VERSION }}

      - name: Install dependencies
        run: npm ci
      - name: Audit npm
        run: npm audit --audit-level=high
      - name: Lint
        run: npm run lint
      - name: License check
        run: npm run license-check
      - name: Build
        run: npm run build-release
