name: Release ARLAS-wui-toolkit
run-name: Release ARLAS-wui-toolkit ${{inputs.version}} ${{inputs.stage}} ${{inputs.stage_iteration}}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
      stage:
        type: choice
        description: Stage of the release
        required: true
        options:
        - beta
        - rc
        - stable
      stage_iteration:
        description: Iteration of the release (needed for beta and rc)
        required: false


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Release
      env:
        # secrets are defined here : https://github.com/organizations/gisaia/settings/secrets/actions
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash release-actions.sh -version=${{inputs.version}} -s=${{inputs.stage}} -i=${{inputs.stage_iteration}} -ref_branch=${{ steps.extract_branch.outputs.branch }}
